# Menggunakan base image node:alpine

FROM node:alpine

# Membuat directory app, setting working directory

WORKDIR /usr/src/app

# Copy file package.json dan package-lock.json (jika ada)

COPY package*.json ./

# Menginstal dependency

RUN npm install

# Bundle source

COPY . .

ENV APP_PORT 2694
ENV APP_NAME UNKNOWN
ENV APP_VERSION UNKNOWN
ENV APP_ENVIRONMENT UNKNOWN
ENV APP_TIMEZONE UNKNOWN
ENV APP_LANGUAGE UNKNOWN
ENV APP_KEY UNKNOWN
ENV DB_TIMEZONE UNKNOWN
ENV DB_HOST_DITOKOKU UNKNOWN
ENV DB_PORT_DITOKOKU UNKNOWN
ENV DB_DATABASE_DITOKOKU UNKNOWN
ENV DB_USER_DITOKOKU UNKNOWN
ENV DB_PASSWORD_DITOKOKU UNKNOWN
ENV RECORDS_PER_PAGE UNKNOWN
ENV MAXIMUM_RESPONSE_RECORDS UNKNOWN

RUN echo "APP_PORT="$APP_PORT > .env
RUN echo "APP_NAME="$APP_NAME >> .env
RUN echo "APP_VERSION="$APP_VERSION >> .env
RUN echo "APP_ENVIRONMENT="$APP_ENVIRONMENT >> .env
RUN echo "APP_TIMEZONE="$APP_TIMEZONE >> .env
RUN echo "APP_LANGUAGE="$APP_LANGUAGE >> .env
RUN echo "APP_KEY="$APP_KEY >> .env
RUN echo "DB_TIMEZONE="$DB_TIMEZONE >> .env
RUN echo "DB_HOST_DITOKOKU="$DB_HOST_DITOKOKU >> .env
RUN echo "DB_PORT_DITOKOKU="$DB_PORT_DITOKOKU >> .env
RUN echo "DB_DATABASE_DITOKOKU="$DB_DATABASE_DITOKOKU >> .env
RUN echo "DB_USER_DITOKOKU="$DB_USER_DITOKOKU >> .env
RUN echo "DB_PASSWORD_DITOKOKU="$DB_PASSWORD_DITOKOKU >> .env
RUN echo "RECORDS_PER_PAGE="$RECORDS_PER_PAGE >> .env
RUN echo "MAXIMUM_RESPONSE_RECORDS="$MAXIMUM_RESPONSE_RECORDS >> .env


# Expose port (for documentation)

EXPOSE 3000

# Run the app

CMD [ "node", "src/app.js"]